{"name": "test_wrong_login", "status": "passed", "description": "\"test_wrong_login\" is the test that try auth with wrong login", "steps": [{"name": "authorization wrong login", "status": "passed", "start": 1694858070283, "stop": 1694858080411}], "attachments": [{"name": "stdout", "source": "0be208a9-4796-4c73-9f90-e0ce16981fe8-attachment.txt", "type": "text/plain"}], "start": 1694858062400, "stop": 1694858080575, "uuid": "6706376a-ae76-46ab-bbfc-29eace4e7375", "historyId": "895cdcf3adb0628e34b928aea7619ec2", "testCaseId": "895cdcf3adb0628e34b928aea7619ec2", "fullName": "tests.test_authorizations#test_wrong_login", "labels": [{"name": "tag", "value": "order(1)"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorizations"}, {"name": "host", "value": "MacBook-Air-Aleksej.local"}, {"name": "thread", "value": "18514-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorizations"}]}